AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AeroNode Inventory Service – SAM template
  Deploys two Lambda functions: Backend & Execution Backend

# ──────────────────────────────────────────────
# Global defaults shared by all functions
# ──────────────────────────────────────────────
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        # ── RDS credentials ──
        DB_HOST: aeronode-rds-server
        DB_PORT: "5432"
        DB_USER: postgres
        DB_PASSWORD: "Admin$1234"
        DB_NAME: AeroNode-Central-DB
    VpcConfig:
      SubnetIds:
        - subnet-09ce27b883b875abe
        - subnet-018a573fd1dd55c65
      SecurityGroupIds:
        - sg-0caa1008d144d961d

Resources:
  # ════════════════════════════════════════════
  #  1. Backend Lambda  (apps/backend)
  # ════════════════════════════════════════════
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aeronode-backend
      Description: Main backend API (auth, health, etc.)
      CodeUri: apps/backend/
      Handler: src/index.handler
      Events:
        # Routes under /api/backend/* → this Lambda
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /api/backend/{proxy+}
            Method: ANY
            ApiId: !Ref SharedApi
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /api/backend
            Method: ANY
            ApiId: !Ref SharedApi
      # Environment:
      #   Variables:
      #     SOME_BACKEND_SPECIFIC_VAR: value
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts

  # ════════════════════════════════════════════
  #  2. Execution Backend Lambda  (apps/executionBackend)
  # ════════════════════════════════════════════
  ExecutionBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aeronode-execution-backend
      Description: Execution backend API (flights, scheduling, etc.)
      CodeUri: apps/executionBackend/
      Handler: src/index.handler
      Events:
        # Routes under /api/execution/* → this Lambda
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /api/execution/{proxy+}
            Method: ANY
            ApiId: !Ref SharedApi
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /api/execution
            Method: ANY
            ApiId: !Ref SharedApi
      Environment:
        Variables:
          AMADEUS_API_KEY: "vg7b10LesGKTaAwKZun65FxAnbjMKahb"
          AMADEUS_API_SECRET: "X0IvALEms2Z8k8TN"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts

  # ════════════════════════════════════════════
  #  Shared API Gateway (HTTP API)
  # ════════════════════════════════════════════
  SharedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"            # tighten for production
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"

# ──────────────────────────────────────────────
# Outputs
# ──────────────────────────────────────────────
Outputs:
  ApiUrl:
    Description: Base URL of the shared API Gateway
    Value: !Sub "https://${SharedApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    # Backend:          {ApiUrl}/api/backend/...
    # Execution Backend: {ApiUrl}/api/execution/...
